name: Build

on:
  workflow_call:
    inputs:
      docker_directory:
        required: true
        type: sting
      ecr_repository:
        required: true
        type: string
      java_version:
        type: string
        required: true

jobs:
  build_test:
    env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ github.event.inputs.java_version }}
        uses: actions/setup-java@v3
        with:
          java-version: '${{ github.event.inputs.java_version }}'
          distribution: 'temurin'
          #cache: maven
      - name: Retrieve project version
        id: get_version
        run: |
          echo "PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout  --file pom.xml)" >> $GITHUB_ENV
      - name: Maven compile
        run: mvn -B compile --file pom.xml
      - name: Maven integration test
        run: mvn -B integration-test --file pom.xml
      - name: Maven integration test
        run: mvn -B test --file pom.xml
      - name: Maven install
        run: mvn -B install -Pdocker -DskipTests=true --file pom.xml
      - name: Dependency check
        uses: dependency-check/Dependency-Check_Action@main
        env:
          # actions/setup-java@v1 changes JAVA_HOME, so it needs to be reset to match the Dependency check image
          JAVA_HOME: /opt/jdk
        id: Dependency check
        with:
          project: 'test'
          path: '.'
          format: 'HTML'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --failOnCVSS 7
            --enableRetired
      - name: Upload Test results
        if: ${{ always() }}
        uses: actions/upload-artifact@master
        with:
          name: Dependency check report
          path: ${{github.workspace}}/reports
      - name: Docker build
        run: |
          docker build -f ${{ github.event.inputs.docker_directory }}/target/Dockerfile ${{ github.event.inputs.docker_directory }}/target -t $ECR_REPOSITORY:$PROJECT_VERSION
